version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: autoflex-postgres
    restart: always
    environment:
      POSTGRES_DB: autoflex
      POSTGRES_USER: autoflex
      POSTGRES_PASSWORD: autoflex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - autoflex-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: autoflex-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - autoflex-network

volumes:
  postgres_data:

networks:
  autoflex-network:
    driver: bridge
